/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 minitruck.gltf 
Author: ARDmation (https://sketchfab.com/ardmation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-e-2200-pickup-truck-3d6fe0687b074e2bb57bd931a9621d58
Title: Mazda E 2200 Pickup Truck
*/

import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/objects/minitruck/minitruck.gltf')
  const ref = useRef();

  // This function runs every frame, rotating the object
  useFrame(() => {
    ref.current.rotation.y += 0.007; // Adjust rotation speed as needed
  });
  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
      // Initial position [x, y, z]
      position={[0, -1, 0]}
      // Initial rotation [x, y, z] in radians
      rotation={[0, 0, 0]}
      // Initial scale [x, y, z]
      scale={[.85, .85, .85]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Light2} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Mirrors} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.WhitePlastic} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Seats} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Cap.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Chassis} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Light1} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Paint} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['tier_1o.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Plate} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.wp_tire_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/objects/minitruck/minitruck.gltf')
